### ISSUE TITLE
Trying to rebuild Algorands auction demo sample with the SDK.

### ISSUE THREAD

**Issue by bernhardrieder** [CareBoo/unity-algorand-sdk#96] opened 2022-03-13 20:58 UTC
I've been trying to quick and dirty rebuild the [auction demo](https://github.com/algorand/auction-demo) sample from the Algorand repo according to the [Algorand Developer Docs](https://developer.algorand.org/docs/get-started/dapps/pyteal/) mostly because I wanted to see how things go with smart contracts. Now, I tried to transcribe everything from the official Python SDK to your SDK and I'm not 100% sure if everything was transcribed perfectly but this [repo](https://github.com/bernhardrieder/unity-algorand-sdk-examples) is what I've ended up with so far. Right now, I'm facing a few issues which you might be able to help with - I'm honestly not sure if they're bugs in the SDK or if I'm misusing the SDK/API. (I'm running all the examples with the sandbox as described in the [Algorand Developer Docs](https://developer.algorand.org/docs/get-started/dapps/pyteal/))

### Issue 1: Formatter for type AlgoSdk.TransactionType[] could not be found...
I started writing the code with version **2.0.0-pre.2** and I've tried to update to the **_2.0.0_** version today. However, any version after the version _**2.0.0-pre.2**_ throws the following exception about missing the `AlgoSdk.TransactionType[]` formatter when trying to call/fetch `KmdClient.ListWallets()` ([link to code](https://github.com/bernhardrieder/unity-algorand-sdk-examples/blob/5f5a9f7f500167a8bd6904488a0db0a247cb3ad4/Assets/Scripts/AlgoSdk.Examples/AuctionDemo/Setup.cs#L33))
```
NotImplementedException: Formatter for type AlgoSdk.TransactionType[] could not be found...
AlgoSdk.AlgoApiFormatterCache`1[T]..cctor () (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.3/CareBoo.AlgoSdk/Serialization/AlgoApiFormatterCache.cs:18)
Rethrow as TypeInitializationException: The type initializer for 'AlgoSdk.AlgoApiFormatterCache`1' threw an exception.
AlgoSdk.AlgoApiField`1+<>c__DisplayClass18_0`1[TAlgoApiObject,T].<Assign>g__deserializeJson|1 (TAlgoApiObject& obj, AlgoSdk.Json.JsonReader& reader) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.3/CareBoo.AlgoSdk/Serialization/AlgoApiField.cs:98)
AlgoSdk.AlgoApiObjectFormatter`1[T].Deserialize (AlgoSdk.Json.JsonReader& reader) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.3/CareBoo.AlgoSdk/Serialization/AlgoApiObjectFormatter.cs:56)
Rethrow as SerializationException: Got exception when deserializing "supported_txs" for type AlgoSdk.Wallet
AlgoSdk.AlgoApiObjectFormatter`1[T].Deserialize (AlgoSdk.Json.JsonReader& reader) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.3/CareBoo.AlgoSdk/Serialization/AlgoApiObjectFormatter.cs:60)
AlgoSdk.Formatters.ArrayFormatter`1[T].Deserialize (AlgoSdk.Json.JsonReader& reader) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.3/CareBoo.AlgoSdk/Serialization/Formatters/Generics/ArrayFormatter.cs:22)
AlgoSdk.AlgoApiField`1+<>c__DisplayClass18_0`1[TAlgoApiObject,T].<Assign>g__deserializeJson|1 (TAlgoApiObject& obj, AlgoSdk.Json.JsonReader& reader) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.3/CareBoo.AlgoSdk/Serialization/AlgoApiField.cs:98)
AlgoSdk.AlgoApiObjectFormatter`1[T].Deserialize (AlgoSdk.Json.JsonReader& reader) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.3/CareBoo.AlgoSdk/Serialization/AlgoApiObjectFormatter.cs:56)
Rethrow as SerializationException: Got exception when deserializing "wallets" for type AlgoSdk.ListWalletsResponse
AlgoSdk.AlgoApiObjectFormatter`1[T].Deserialize (AlgoSdk.Json.JsonReader& reader) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.3/CareBoo.AlgoSdk/Serialization/AlgoApiObjectFormatter.cs:60)
AlgoSdk.AlgoApiSerializer.DeserializeJson[T] (Unity.Collections.NativeText text) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.3/CareBoo.AlgoSdk/AlgoApi/AlgoApiSerializer.cs:92)
AlgoSdk.AlgoApiSerializer.DeserializeJson[T] (Unity.Collections.NativeArray`1[T] bytes) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.3/CareBoo.AlgoSdk/AlgoApi/AlgoApiSerializer.cs:63)
AlgoSdk.AlgoApiSerializer.Deserialize[T] (Unity.Collections.NativeArray`1[T] bytes, AlgoSdk.ContentType contentType) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.3/CareBoo.AlgoSdk/AlgoApi/AlgoApiSerializer.cs:40)
AlgoSdk.AlgoApiSerializer.Deserialize[T] (System.Byte[] bytes, AlgoSdk.ContentType contentType) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.3/CareBoo.AlgoSdk/AlgoApi/AlgoApiSerializer.cs:26)
AlgoSdk.AlgoApiResponse`1[T]..ctor (AlgoSdk.AlgoApiResponse response) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.3/CareBoo.AlgoSdk/AlgoApi/AlgoApiResponse.cs:91)
AlgoSdk.AlgoApiResponse`1[T].op_Implicit (AlgoSdk.AlgoApiResponse response) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.3/CareBoo.AlgoSdk/AlgoApi/AlgoApiResponse.cs:127)
AlgoSdk.AlgoApiRequest+Awaiter`1[TResponse].GetResult () (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.3/CareBoo.AlgoSdk/AlgoApi/AlgoApiRequest.cs:425)
AlgoSdk.Examples.AuctionDemo.Setup.GetGenesisAccounts () (at Assets/Scripts/AlgoSdk.Examples/AuctionDemo/Setup.cs:33)
```

### Issue 2: msgpack decode error [pos 82]: bytes/string in stream must decode into slice/array of bytes, not [][]uint8
This issue arises everytime I tried to pass application arguments with a transaction. I've tried a few different approaches but I've always ended up with this error and I don't know what's going on. I also tried to reimplement a [dotnet algorand sdk example](https://github.com/RileyGe/dotnet-algorand-sdk/blob/master/sdk-examples/V2/contract/StatefulContract.cs) with hope that it resembles your SDK in a way but I've ended up with the exact same error again!

This happened with `Transaction.AppCall` ([example](https://github.com/bernhardrieder/unity-algorand-sdk-examples/blob/5f5a9f7f500167a8bd6904488a0db0a247cb3ad4/Assets/Scripts/AlgoSdk.Examples/DotNetSDKStatefulContract/StatefulContractExample.cs#L344)) as well with arguments added to `Transaction.AppCreate` ([example](https://github.com/bernhardrieder/unity-algorand-sdk-examples/blob/5f5a9f7f500167a8bd6904488a0db0a247cb3ad4/Assets/Scripts/AlgoSdk.Examples/AuctionDemo/Operations.cs#L64)). Please note that I have no clue if I constructed the app args byte array in the correct way. Any help regarding this would be much appreciated. :D

### Issue 3: KeyNotFoundException: Could not find the key, "global-state-delta", for any fields on AlgoSdk.PendingTransaction
Once again, an issue with app arguments. This time the issue appears when waiting for the pending transaction after creating a `Transaction.AppCall` with app args which are `null` ([example](https://github.com/bernhardrieder/unity-algorand-sdk-examples/blob/5f5a9f7f500167a8bd6904488a0db0a247cb3ad4/Assets/Scripts/AlgoSdk.Examples/DotNetSDKStatefulContract/StatefulContractExample.cs#L68)). Again, not sure if I'm just not using the SDK correctly or if this shouldn't happen. Here's the callstack:
```
KeyNotFoundException: Could not find the key, "global-state-delta", for any fields on AlgoSdk.PendingTransaction
AlgoSdk.AlgoApiField`1+Map`1[TAlgoApiObject,TKey].GetField (TKey key) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.2/CareBoo.AlgoSdk/Serialization/AlgoApiField.cs:137)
AlgoSdk.AlgoApiObjectFormatter`1[T].Deserialize (AlgoSdk.MessagePack.MessagePackReader& reader) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.2/CareBoo.AlgoSdk/Serialization/AlgoApiObjectFormatter.cs:78)
Rethrow as SerializationException: Got exception when deserializing "global-state-delta" for type AlgoSdk.PendingTransaction
AlgoSdk.AlgoApiObjectFormatter`1[T].Deserialize (AlgoSdk.MessagePack.MessagePackReader& reader) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.2/CareBoo.AlgoSdk/Serialization/AlgoApiObjectFormatter.cs:82)
AlgoSdk.AlgoApiSerializer.DeserializeMessagePack[T] (Unity.Collections.NativeArray`1[T] bytes) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.2/CareBoo.AlgoSdk/AlgoApi/AlgoApiSerializer.cs:116)
AlgoSdk.AlgoApiSerializer.Deserialize[T] (Unity.Collections.NativeArray`1[T] bytes, AlgoSdk.ContentType contentType) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.2/CareBoo.AlgoSdk/AlgoApi/AlgoApiSerializer.cs:41)
AlgoSdk.AlgoApiSerializer.Deserialize[T] (System.Byte[] bytes, AlgoSdk.ContentType contentType) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.2/CareBoo.AlgoSdk/AlgoApi/AlgoApiSerializer.cs:26)
AlgoSdk.AlgoApiResponse`1[T]..ctor (AlgoSdk.AlgoApiResponse response) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.2/CareBoo.AlgoSdk/AlgoApi/AlgoApiResponse.cs:91)
AlgoSdk.AlgoApiResponse`1[T].op_Implicit (AlgoSdk.AlgoApiResponse response) (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.2/CareBoo.AlgoSdk/AlgoApi/AlgoApiResponse.cs:127)
AlgoSdk.AlgoApiRequest+Awaiter`1[TResponse].GetResult () (at Library/PackageCache/com.careboo.unity-algorand-sdk@2.0.0-pre.2/CareBoo.AlgoSdk/AlgoApi/AlgoApiRequest.cs:425)
AlgoSdk.Examples.AuctionDemo.Util.WaitForTransaction (AlgoSdk.IAlgodClient client, AlgoSdk.TransactionId txid, System.UInt64 timeout) (at Assets/Scripts/AlgoSdk.Examples/AuctionDemo/Util.cs:23)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) (at Library/PackageCache/com.cysharp.unitask@2.2.5/Runtime/UniTaskCompletionSource.cs:244)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) (at Library/PackageCache/com.cysharp.unitask@2.2.5/Runtime/CompilerServices/StateMachineRunner.cs:342)
Cysharp.Threading.Tasks.UniTask`1+Awaiter[T].GetResult () (at Library/PackageCache/com.cysharp.unitask@2.2.5/Runtime/UniTask.cs:653)
AlgoSdk.Examples.StatefulContract.StatefulContractExample.CallApp (AlgoSdk.IAlgodClient client, AlgoSdk.Examples.AuctionDemo.Account sender, System.UInt64 appId, System.Collections.Generic.List`1[T] args) (at Assets/Scripts/AlgoSdk.Examples/DotNetSDKStatefulContract/StatefulContractExample.cs:362)
```

**Comment by jasonboukheir** [comment] 2022-03-15 12:56
--First Issue--
I refactored the serialization logic and seemed to have broken it. Could you try version 2.1.0-pre.5? Let me know if you're still seeing issues.

To go more into detail, the serializer refers to a dictionary of formatters when trying to serialize or deserialize a type. The formatter dictionary is represented by the class: AlgoSdk.AlgoApiFormatterLookup. ​When you get those errors, it means that type isn't found in the dictionary. In this case, AlgoApiFormatterLookup​ doesn't have a formatter for the type Transaction.Type[]​. One workaround is to add the formatter yourself before your game starts:
AlgoApiFormatterLookup.Add<Transaction.Type[]>(ArrayFormatter<Transaction.Type[]>.Instance);​

--Second Issue--
Could you show me the args that you're sending? Definitely sounds like a bug. It would make it easier for me to set up an integration test for it.

--Third Issue--
This is also a bug. If there is a field in the JSON or msgpack that the SDK doesn't recognize, it throws an error. This is really useful behavior when developing the SDK, but very annoying for the user. A new JSON field should not be a breaking change. There are a couple things that should be done about this:
Add that field to PendingTransaction​
Set default behavior in the formatter to warn if there is a field it does not recognize. Add an option to throw an exception if there is a field it does not recognize for testing.
Add the ability to run integration tests in the CI pipeline by setting up a sandbox server.

**Comment by jasonboukheir** [comment] 2022-03-15 12:56
Hi Bernhard,

Thanks for making the issue, I'm going to respond there :).

Cheers,
Jason

------- Original Message -------

**Comment by bernhardrieder** [comment] 2022-03-15 19:32
Hey, first and foremost, thanks for creating this awesome SDK and thanks for taking a look at this so swiftly! I apologize for refering to my repo so sneakily, I definitely could have done a better job there 😀 The idea was to fully re-create the auction demo example from the developer docs and then push it into your repo as part of the examples so that everyone can take a look how one you'd write the auction demo from scratch with the SDK, as a more in-depth example besides the other basic ones.


**Now, regarding the issues:** 
I tried version `2.1.0-pre.5` but it's still the same issue. 

Thus, trying to add `AlgoApiFormatterLookup.Add<TransactionType[]>(ArrayFormatter<TransactionType>.Instance);` helps getting rid of the initial error but will result in a new one about `Formatter for type AlgoSdk.TransactionType could not be found...`.
Now, I thought of adding another line of code to this with `AlgoApiFormatterLookup.Add<TransactionType>(new ByteEnumFormatter<TransactionType>());` but it seems this ends up in an endless loop. I'd think this is the right formatter for the job because `TransactionType` is an `enum : byte` but I could be totally wrong here.

If you want to try this out with my repository, then you can either start the `AuctionDemo` scene and it'll appear right at the start or try to run the tests (see picture) with a running local sandbox. ([this is the failing test code](https://github.com/bernhardrieder/unity-algorand-sdk-examples/blob/5f5a9f7f500167a8bd6904488a0db0a247cb3ad4/Assets/Scripts/AlgoSdk.Examples.Test/AuctionDemo/SetupTest.cs#L38))
![image](https://user-images.githubusercontent.com/7604578/158454101-3cc1a832-36e1-4584-a574-b0cce054dd8c.png)

Note that, after version `2.0.0-pre.2` the `GetKmdClient` test failed with `Formatter for type Unity.Collections.FixedString64Bytes[] could not be found...` which is fixed with version `2.1.0-pre.5`

I updated my respository with the version, so you can just grab latest if you want to test it.

**Comment by jasonboukheir** [comment] 2022-03-16 17:25
kk found one more issue. I changed the codegen logic recently, so there were no formatters added for any of the enums 😱 . Issue is tracked here: https://github.com/CareBoo/unity-algorand-sdk/issues/99

And no worries, this is a passion project. It lets me learn so much about Algorand :). Thanks for using it and giving me feedback! It really motivates me to make it better.

**Comment by jasonboukheir** [comment] 2022-03-18 00:29
Hi @bernhardrieder , I just tried running your tests with the latest version, 2.1.0, and they all passed. Going to close this out!

**Comment by bernhardrieder** [comment] 2022-03-19 11:40
Unfortunately there might have been a miscommunication on my side. I didn't put the actual auction demo example into the tests as I was testing it by running the game within the editor and I'm still getting the `msgpack decode error [pos 82]: bytes/string in stream must decode into slice/array of bytes, not [][]uint8` error when trying to send any arguments, with the latest version. 

I added it to the tests now if you want to grab the latest version from the repository and run the tests again to see the error.

**Comment by jasonboukheir** [comment] 2022-03-19 17:59
Hey @bernhardrieder , no it's definitely my bad. You were very clear. I forgot about the second issue, so thank you for bringing it back up. Reopened the issue.

One thing I noticed is that you are sending app arguments with your create app transaction. I figure you might just have those to test it out, but that looks kind of strange. In the [Algorand documentation on transactions](https://developer.algorand.org/docs/get-details/transactions/#application-create-transaction), app create transactions are not supposed to have application arguments.

Anatomy of the request:
```
completed request
	url: http://localhost:4001/v2/transactions
	uploadedData: gqNzaWfEQC6SkhcestmQZE22iNEsSefyGC8N/nzoYmT3M3jqPTUY9gtnvGEw4LRoiK1mWIkvuEBa2czI4M/iiYtRojKayw6jdHhuiaRhcGFhxEhy/D8lfYsJeRIyNBu2eOmxY414SRfF0YqM5GUVhvGV4AAAAAAAAAAxAdg7t4KFnqAB2Du3goWevgAAAAAAD0JAAAAAAAABhqCkYXBnc4KjbmJzAqNudWkHo2ZlZc0D6KJmdhWjZ2VuqnNhbmRuZXQtdjGiZ2jEIHH3I2wqeW08RiatDDHpb2TP5U/7VEl86K3qq1eRcLFPomx2zQP9o3NuZMQgNMuYonY7EnFWPidVdF5NpwHSxkm/sA4UIAwCl+H8FW+kdHlwZaRhcHBs
	downloadedData: {"message":"msgpack decode error [pos 82]: bytes/string in stream must decode into slice/array of bytes, not [][]uint8"}

	error: HTTP/1.1 400 Bad Request
	method: POST
	downloadHandler.error: 
	GetResponseHeaders(): {
		Access-Control-Allow-Origin: *,
		Content-Type: application/json; charset=UTF-8,
		Vary: Origin,
		Date: Sat, 19 Mar 2022 17:33:56 GMT,
		Content-Length: 121
	}
```

This is the base64 message pack that was uploaded:

```
gqNzaWfEQC6SkhcestmQZE22iNEsSefyGC8N/nzoYmT3M3jqPTUY9gtnvGEw4LRoiK1mWIkvuEBa2czI4M/iiYtRojKayw6jdHhuiaRhcGFhxEhy/D8lfYsJeRIyNBu2eOmxY414SRfF0YqM5GUVhvGV4AAAAAAAAAAxAdg7t4KFnqAB2Du3goWevgAAAAAAD0JAAAAAAAABhqCkYXBnc4KjbmJzAqNudWkHo2ZlZc0D6KJmdhWjZ2VuqnNhbmRuZXQtdjGiZ2jEIHH3I2wqeW08RiatDDHpb2TP5U/7VEl86K3qq1eRcLFPomx2zQP9o3NuZMQgNMuYonY7EnFWPidVdF5NpwHSxkm/sA4UIAwCl+H8FW+kdHlwZaRhcHBs
```

putting that into https://msgpack.dbrgn.ch/, the application arg value is at position 82:
![Screen Shot 2022-03-19 at 10 53 17 AM](https://user-images.githubusercontent.com/5115126/159132729-fc1a4992-8195-499e-943a-ecba9184f773.png)

I'm currently trying to reproduce with a smaller sample in an integration test, but it could just be that the application args aren't being serialized to the correct format. Again, in the [Algorand documentation](https://developer.algorand.org/docs/get-details/transactions/#application-noop-transaction), it looks like they're passing an array of bytes not a single stream of bytes. Right now `Transaction.AppArguments` are just a single `CompiledTeal` (`byte[]`), and not represented as an array. That is likely the issue, but going to make sure I have a test to verify it in a couple of hours.

**Comment by bernhardrieder** [comment] 2022-03-19 21:48
I'm not entirely sure if I'm constructing all the arguments correclty, that's something I didn't really figure out unfortunately, but the entirety of the auction demo was done with the exact structure in Python code as you see it rewritten in C#.

Yep, I wondered if that one byte array did the trick for you and I just assumed that it does and I have to figure out a way to work with that :D 

Thus, even if the arguments work now, then it could still be that I messed up the implementation of the arguments or anything that comes after this step in the auction demo. Therefore, the tests could still fail due to some Python to C# transcription faults.

**Comment by jasonboukheir** [comment] 2022-03-19 23:40
@bernhardrieder got a test verifying the bug you were experiencing. When it gets released, I'll close this issue. I'm pretty sure you'll find other issues; could you open up separate tickets for those?

**Comment by bernhardrieder** [comment] 2022-03-20 08:03
Sure thing! ☺️

**Comment by bernhardrieder** [comment] 2022-03-20 18:56
Good news @jasonboukheir! The latest version works like a charm and I could fix all the remaining bugs in both of the examples. 🎉🎉 I compared the Python version output with my rewritten C# version and it's match! 

Thanks again for your work to make this possible! ❤️

Now, if you want, then I can do a pull request to the examples folder or we'll keep it as it is and you can refer to my repository as an example. I'll see if I can add some more logs and more insight to the example tomorrow.

**Closed** 2022-03-20 18:55 UTC
Labels: bug, released on @pre
